### PR TITLE
PLEASE RELEASE A NEW VERSION WE NEED XCODE 11 SUPPORT

### PR DESCRIPTION
**Pull request by txaiwieser**
Please...

And if possible activate the issues so we can easily report problems and suggestions, the ticketing is complicated and unnecessarily bad.

### CODE REVIEW

**Comment by bielikb** [comment]
Hi @txaiwieser, thanks for your PR.
The latest release of Chat v1.4.3 from master builds fine on latest Xcode 11.2.1.
Please make sure to grab those artifacts.
Thanks

**Comment by bielikb** [comment]
If your issue won't be solved, please head over to our Community forum & open issue there.
Thanks!

https://support.zendesk.com/hc/en-us/community/

Best,
Boris

**Comment by txaiwieser** [comment]
Forcing people to use this community forum instead of Github issues is going to hurt your framework. I bet a lot of issues are not even being communicated anymore. Unfortunately https://support.zendesk.com/hc/en-us/community/

**Comment by bielikb** [comment]
Thanks, I forwarded your concerns to my team.

Here's the correct link:
https://develop.zendesk.com/hc/en-us/community/topics/360000018828-Mobile-SDKs

Have a nice day!

Best,
Boris

**Pull request closed without merging**
